services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:123456@db:5432/postgres
      REDIS_HOST: redis
    restart: always

  worker:
    build: .
    command: python -m app.worker
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:123456@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
    restart: always

  frontend:
    build: .
    command: streamlit run app_ui.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api
    environment:
      API_URL: http://api:8000
    restart: always

volumes:
  postgres_data:
